name: PreTeXt Build & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: oscarlevin/pretext-full

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Add gh-cli
        run: |
          apt-get update
          apt-get install gh jq -y

      - name: Setup git config
        run: |
          git config --global --add safe.directory $(pwd)
          git config user.name "${{ github.actor }} via GitHub Actions"
          git config user.email "${{ github.actor }}@github_actions.no_reply"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt --break-system-packages
          fi

      - name: Build deploy targets
        run: pretext build --deploys

      - name: Run deploy
        run: pretext deploy --no-push

      - name: Push gh-pages branch
        run: git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}